/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.AdminRole;
import backend.LibrarianUser;

import javax.swing.JFrame;

/**
 * @author Ossama
 */
public class AdminRoleWindow extends javax.swing.JFrame implements Node {

    /**
     * Creates new form AdminRoleWindow
     */
    Node parent;
    AddLibrarianWindow addLWindow;
    RemoveLibrarianWindow removeLWindow;
    ViewLibrariansTable viewLTable;
    AdminRole admin = new AdminRole();

    public AdminRoleWindow() {
        initComponents();
        addLWindow = null;
        removeLWindow = null;
        viewLTable = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAddLibrarian = new javax.swing.JButton();
        buttonRemoveLibrarian = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        buttonViewLibrarians = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        buttonAddLibrarian.setBackground(new java.awt.Color(0, 0, 0));
        buttonAddLibrarian.setForeground(new java.awt.Color(255, 255, 255));
        buttonAddLibrarian.setText("Add Librarian");
        buttonAddLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddLibrarianActionPerformed(evt);
            }
        });

        buttonRemoveLibrarian.setBackground(new java.awt.Color(0, 0, 0));
        buttonRemoveLibrarian.setForeground(new java.awt.Color(255, 255, 255));
        buttonRemoveLibrarian.setText("Remove Librarian");
        buttonRemoveLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveLibrarianActionPerformed(evt);
            }
        });

        buttonLogout.setBackground(new java.awt.Color(0, 0, 0));
        buttonLogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        buttonViewLibrarians.setBackground(new java.awt.Color(0, 0, 0));
        buttonViewLibrarians.setForeground(new java.awt.Color(255, 255, 255));
        buttonViewLibrarians.setText("View Librarians");
        buttonViewLibrarians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewLibrariansActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonViewLibrarians, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonRemoveLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonAddLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(buttonAddLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonViewLibrarians, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonRemoveLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddLibrarianActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if (addLWindow == null) {
            addLWindow = new AddLibrarianWindow(admin);
            addLWindow.setTitle("Add Librarian");
        }
        addLWindow.setParentNode(this);
        addLWindow.setVisible(true);
    }//GEN-LAST:event_buttonAddLibrarianActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        admin.logout();
        this.setVisible(false);
        ((JFrame) parent.getParentNode()).setVisible(true);
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonRemoveLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveLibrarianActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if (removeLWindow == null) {
            removeLWindow = new RemoveLibrarianWindow(admin);
            removeLWindow.setTitle("Remove Librarian");
        }
        removeLWindow.setParentNode(this);
        removeLWindow.setVisible(true);
    }//GEN-LAST:event_buttonRemoveLibrarianActionPerformed

    private void buttonViewLibrariansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewLibrariansActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if (viewLTable == null) {
            viewLTable = new ViewLibrariansTable();
            viewLTable.setTitle("View Librarians");
        }
        viewLTable.setParentNode(this);
        LibrarianUser[] librarians = admin.getListOfLibrarians();
        String[][] librariansData = new String[librarians.length][5];
        for (int i = 0; i < librarians.length; i++) {
            String data = librarians[i].lineRepresentation();
            String[] dataSplit = data.split(",");
            librariansData[i][0] = dataSplit[0];
            librariansData[i][1] = dataSplit[1];
            librariansData[i][2] = dataSplit[2];
            librariansData[i][3] = dataSplit[3];
            librariansData[i][4] = dataSplit[4];
        }
        viewLTable.setData(librariansData);
        viewLTable.setVisible(true);
    }//GEN-LAST:event_buttonViewLibrariansActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminRoleWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddLibrarian;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonRemoveLibrarian;
    private javax.swing.JButton buttonViewLibrarians;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParentNode(Node parent) {
        this.parent = parent;
    }

    @Override
    public Node getParentNode() {
        return parent;
    }
}
