/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Book;
import backend.LibrarianRole;
import backend.LibrarianUser;
import backend.StudentBook;
import javax.swing.JFrame;

/**
 *
 * @author Ossama
 */
public class LibrarianRoleWindow extends javax.swing.JFrame implements Node {

    /**
     * Creates new form LibrarianRoleWindow
     */
    Node parent;
    LibrarianRole librarian = new LibrarianRole();
    AddBookWindow addBWindow;
    ViewBooksTable viewBTable;
    ViewBorrowedBooksTable viewBBTable;
    BorrowBookWindow borrowBWindow;
    ReturnBookWindow returnBWindow;

    public LibrarianRoleWindow() {
        initComponents();
        addBWindow = null;
        viewBTable = null;
        borrowBWindow = null;
        viewBBTable = null;
        returnBWindow=null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAddBook = new javax.swing.JButton();
        buttonBorrowBook = new javax.swing.JButton();
        buttonViewBorrowedBooks = new javax.swing.JButton();
        buttonViewBooks = new javax.swing.JButton();
        buttonReturnBook = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        buttonAddBook.setBackground(new java.awt.Color(0, 0, 0));
        buttonAddBook.setForeground(new java.awt.Color(255, 255, 255));
        buttonAddBook.setText("Add Book");
        buttonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddBookActionPerformed(evt);
            }
        });

        buttonBorrowBook.setBackground(new java.awt.Color(0, 0, 0));
        buttonBorrowBook.setForeground(new java.awt.Color(255, 255, 255));
        buttonBorrowBook.setText("Borrow Book");
        buttonBorrowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrowBookActionPerformed(evt);
            }
        });

        buttonViewBorrowedBooks.setBackground(new java.awt.Color(0, 0, 0));
        buttonViewBorrowedBooks.setForeground(new java.awt.Color(255, 255, 255));
        buttonViewBorrowedBooks.setText("View Borrowed Books");
        buttonViewBorrowedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewBorrowedBooksActionPerformed(evt);
            }
        });

        buttonViewBooks.setBackground(new java.awt.Color(0, 0, 0));
        buttonViewBooks.setForeground(new java.awt.Color(255, 255, 255));
        buttonViewBooks.setText("View Books");
        buttonViewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewBooksActionPerformed(evt);
            }
        });

        buttonReturnBook.setBackground(new java.awt.Color(0, 0, 0));
        buttonReturnBook.setForeground(new java.awt.Color(255, 255, 255));
        buttonReturnBook.setText("Return Book");
        buttonReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnBookActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonViewBorrowedBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonBorrowBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonViewBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAddBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(buttonAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonViewBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(buttonBorrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonViewBorrowedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddBookActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if (addBWindow == null) {
            addBWindow = new AddBookWindow(librarian);
            addBWindow.setTitle("Add Book");
        }
        addBWindow.setParentNode(this);
        addBWindow.setVisible(true);
    }//GEN-LAST:event_buttonAddBookActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        librarian.logout();
        this.setVisible(false);
        ((JFrame) parent.getParentNode()).setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void buttonViewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewBooksActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if (viewBTable == null) {
            viewBTable = new ViewBooksTable();
            viewBTable.setTitle("View Librarians");
        }
        viewBTable.setParentNode(this);
        Book[] books = librarian.getListOfBooks();
        String[][] booksData = new String[books.length][5];
        for (int i = 0; i < books.length; i++) {
            String data = books[i].lineRepresentation();
            String[] dataSplit = data.split(",");
            booksData[i][0] = dataSplit[0];
            booksData[i][1] = dataSplit[1];
            booksData[i][2] = dataSplit[2];
            booksData[i][3] = dataSplit[3];
            booksData[i][4] = dataSplit[4];
        }
        viewBTable.setData(booksData);
        viewBTable.setVisible(true);

    }//GEN-LAST:event_buttonViewBooksActionPerformed

    private void buttonViewBorrowedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewBorrowedBooksActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if (viewBBTable == null) {
            viewBBTable = new ViewBorrowedBooksTable();
            viewBBTable.setTitle("View Borrowed Books");
        }
        viewBBTable.setParentNode(this);
        StudentBook[] borrowedBooks = librarian.getListOfBorrowingOperations();
        String[][] borrowedBooksData = new String[borrowedBooks.length][3];
        for (int i = 0; i < borrowedBooks.length; i++) {
            String data = borrowedBooks[i].lineRepresentation();
            String[] dataSplit = data.split(",");
            borrowedBooksData[i][0] = dataSplit[0];
            borrowedBooksData[i][1] = dataSplit[1];
            borrowedBooksData[i][2] = dataSplit[2];

        }
        viewBBTable.setData(borrowedBooksData);
        viewBBTable.setVisible(true);
    }//GEN-LAST:event_buttonViewBorrowedBooksActionPerformed

    private void buttonBorrowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrowBookActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if (borrowBWindow == null) {
            borrowBWindow = new BorrowBookWindow(librarian);
            borrowBWindow.setTitle("Borrow Book");
        }
        borrowBWindow.setParentNode(this);
        borrowBWindow.setVisible(true);
    }//GEN-LAST:event_buttonBorrowBookActionPerformed

    private void buttonReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnBookActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if (returnBWindow == null) {
            returnBWindow = new ReturnBookWindow(librarian);
            returnBWindow.setTitle("Return Book");
        }
        returnBWindow.setParentNode(this);
        returnBWindow.setVisible(true);
    }//GEN-LAST:event_buttonReturnBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianRoleWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton buttonAddBook;
    private javax.swing.JButton buttonBorrowBook;
    private javax.swing.JButton buttonReturnBook;
    private javax.swing.JButton buttonViewBooks;
    private javax.swing.JButton buttonViewBorrowedBooks;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParentNode(Node parent) {
        this.parent = parent;
    }

    @Override
    public Node getParentNode() {
        return parent;
    }
}
